export AMD_VULKAN_ICD=RADV
export BROWSER=google-chrome-stable
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export MAIL=thunderbird
# export TERM=alacritty
export EDITOR=nvim
export VISUAL=nvim
export PATH="${HOME}/.poetry/bin:${PYENV_ROOT}/bin:${HOME}/.local/bin:${PATH}"
export PYENV_ROOT="${HOME}/.pyenv"
export DEVELOPMENT_FOLDER="${HOME}/dev"
export AUTOENV_ENV_FILENAME='.envrc'
export MAKEFLAGS='-j16'
