#! /bin/sh

picom &
sxhkd &
unclutter &
dunst &
pidswallow --loop &
$HOME/.config/polybar/launch.sh &
feh --bg-center /home/coma/Pictures/wallpapers/background-ching-chong.png &

bspc monitor -d TTY WEB LAB MED MISC

bspc config border_width            2
bspc config window_gap              12

bspc config normal_border_color     "#000000"
bspc config focused_border_color    "#9e434c"
bspc config presel_feedback_color   "#9e434c"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Screenkey manage=off
#bspc rule -a code-oss border=off
#bspc rule -a Gimp desktop='^8' state=floating follow=on
