#!/usr/bin/env bash

count=0
disconnected=""
wireless_connected=""
ethernet_connected=""

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 google.com) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 5
        else
            echo "$wireless_connected" ; sleep 5
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
